server:
  port: 8888
spring:
  datasource:
    name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hand_training?serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 192.168.43.15
  rabbitmq:
    host: 192.168.43.15
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath:com/hand/springbootmybatis/mapper/xml/*.xml

